iai-group/arXivDigest

- api/database.py
- sample/system.py
Small fix for the recommender system
> Feature/#19 Small fix for the recommender system

- Setup.md
- sample/README.md
> Documentation for setup and sample system

- scraper/categories.py
- scraper/storeMetadata.py
Changed method of getting category names to hopefully not needing to update the names again.
> Fixed sub category names

- arxivdigest/frontend/database/general.py
- arxivdigest/frontend/templates/living_lab.html
- arxivdigest/frontend/views/general.py
- redirects to livinglab page after system registration
- system/register -> livinglab/register
- removed contact name, organization and email from system list in livinglab
- added own line with this information above table
Don't mind branch name should be #74 instead of #72
> closes #73 #74 #75

- arxivdigest/api/app.py
- arxivdigest/api/database.py
- arxivdigest/api/utils.py
- arxivdigest/core/config.py
- arxivdigest/core/mail/mail_server.py
- arxivdigest/frontend/app.py
- arxivdigest/frontend/database/general.py
- arxivdigest/frontend/models/errors.py
- arxivdigest/frontend/models/system.py
- arxivdigest/frontend/models/user.py
- arxivdigest/frontend/models/validate.py
- arxivdigest/frontend/utils.py
- arxivdigest/frontend/views/articles.py
- interleave/database.py
- interleave/interleave.py
- interleave/tdm.py
- sample/index.py
- sample/init_index.py
- scraper/categories.py
- scripts/evaluation.py
fixed missing quotes and changed double quotes to single quotes on author and copyright
> closes #83

- arxivdigest/api/app.py
- arxivdigest/api/utils.py
Don't know if you want to merge it or just pull this branch but created a PR so you'd see it.
Guess this is what you meant, this is the result of calling the /debug_header endpoint:
[
{
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
"Accept-Encoding": "gzip, deflate, br", 
"Accept-Language": "en-US,en;q=0.9,nb-NO;q=0.8,nb;q=0.7", 
"Cache-Control": "max-age=0", 
"Connection": "keep-alive", 
"Cookie": "auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODQ2NjI1MTUsInN1YiI6MiwiYWRtaW4iOnRydWUsImVtYWlsIjoiYUBhYSJ9.qWhi4yAuz_Bs9DdVXZb-z5fz3mZjbMCraf8R99bqqRs", 
"Dnt": "1", 
"Host": "127.0.0.1:5000", 
"Sec-Fetch-Dest": "document", 
"Sec-Fetch-Mode": "navigate", 
"Sec-Fetch-Site": "none", …
> Debugging apikey

- arxivdigest/api/README.md
- arxivdigest/api/utils.py
- sample/index.py
- sample/system.py
The system will not work unless the other PR is also merged, as the keywords are not changed to topics before that.
> changed api_key field in header

- arxivdigest/frontend/templates/base.html
- arxivdigest/frontend/templates/index.html
- arxivdigest/frontend/templates/living_lab.html
- arxivdigest/frontend/templates/login.html
- arxivdigest/frontend/templates/profile.html
- arxivdigest/frontend/uncompiled_assets/css/style.css
Not done yet, but I'd like to merge changes so far
> Styling login and profile pages

- arxivdigest/api/database.py
> closes #136

- arxivdigest/core/database/users_db.py
- arxivdigest/core/mail/digest_mail.py
- arxivdigest/core/mail/templates/confirm_email.tmpl
- arxivdigest/core/mail/templates/email_base.tmpl
- arxivdigest/core/mail/templates/systemActivation.tmpl
- arxivdigest/core/mail/templates/weekly.tmpl
- arxivdigest/frontend/database/general.py
- arxivdigest/frontend/models/user.py
- arxivdigest/frontend/templates/modify.html
- arxivdigest/frontend/templates/profile.html
- arxivdigest/frontend/templates/unsubscribed.html
- arxivdigest/frontend/templates/user_profile_form.html
- arxivdigest/frontend/views/general.py
- db/database_v1.sql
**SQL to run:**
alter table users
add column unsubscribe_trace char(36) unique default null;
> Feature/#124 suspend notifications and  #133 base_email

- tests/test_interleaving.py
> Test for interleaver

- arxivdigest/core/scraper/categories.py
> fixed broken category scraper

- arxivdigest/api/app.py
- arxivdigest/api/database.py
- arxivdigest/connector/__init__.py
- config.json
endpoint for fetching all current topics in the database
> closes #162

- arxivdigest/frontend/uncompiled_assets/javascript/topics.js
think the `` quotes used for multiline strings might have created some issues.
Also added extra '' to close the data-value value
> fixed creation of topic buttons

- setup.py
included template needed for feedback page that was not included
> fixed feedback form

- arxivdigest/core/mail/templates/email_base.tmpl
- arxivdigest/core/mail/templates/weekly.tmpl
- text align left
- font changes
- rename save and remove empty line
- autor list black
- changed wording on some sentences
> closes email styling

- arxivdigest/frontend/uncompiled_assets/javascript/evaluation.js
quick fix for plots not starting at 0
> begin at zero

- arxivdigest/frontend/uncompiled_assets/javascript/evaluation.js
- arxivdigest/frontend/views/evaluation.py
renamed and removed plots as newest specification
> removed cumulative nomralized rewards

- scripts/index_open_research_corpus.py
Replace `parallel_bulk` with `bulk` and increase chunk size.
> Fix S2ORC Elasticsearch indexing script

- scripts/README.md
- scripts/gen_semantic_scholar_suggestions.py
- scripts/index_open_research_corpus.py
Replace `--hosts` option with single `--host` option.
> Tweak S2ORC Elasticsearch indexing and S2 suggestion generation scripts

- arxivdigest/core/mail/digest_mail.py
Closes #197
Most changes come from black formatting.
The main change in this PR is in `send_digest_mail` where new connection is created for every mail batch.
> Create new mail server connection per batch

- arxivdigest/api/validator.py
- arxivdigest/frontend/models/user.py
- arxivdigest/frontend/views/general.py
Fixes #199
Changes
* Black formatting
* Change of comparinsons from 'is' to '==' when comparing to literal
* Fix redirect when confirming email
> Update comparisons to be pythonic
